//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenUtauMobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenUtauMobile.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Abort 的本地化字符串。
        /// </summary>
        internal static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional Singer Search Paths 的本地化字符串。
        /// </summary>
        internal static string AdditionalSingerPath {
            get {
                return ResourceManager.GetString("AdditionalSingerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add extra folders for Singer Manager to search singers, so you can extract singer install packages into anywhere you want in External Storage Path. 的本地化字符串。
        /// </summary>
        internal static string AdditionalSingerPathTooltip {
            get {
                return ResourceManager.GetString("AdditionalSingerPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AI is processing... 的本地化字符串。
        /// </summary>
        internal static string AIProcessing {
            get {
                return ResourceManager.GetString("AIProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance &amp; Language 的本地化字符串。
        /// </summary>
        internal static string AppearanceAndLanguage {
            get {
                return ResourceManager.GetString("AppearanceAndLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Mobile 的本地化字符串。
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Mobile Runtime Exception 的本地化字符串。
        /// </summary>
        internal static string AppRuntimeException {
            get {
                return ResourceManager.GetString("AppRuntimeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The imported project contains the following tempo markers. Do you want to use them? 的本地化字符串。
        /// </summary>
        internal static string AskIfImportTempo {
            get {
                return ResourceManager.GetString("AskIfImportTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At bar 的本地化字符串。
        /// </summary>
        internal static string AtBarText {
            get {
                return ResourceManager.GetString("AtBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At work 的本地化字符串。
        /// </summary>
        internal static string AtWork {
            get {
                return ResourceManager.GetString("AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audio Export Options 的本地化字符串。
        /// </summary>
        internal static string AudioExportOptions {
            get {
                return ResourceManager.GetString("AudioExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author: 的本地化字符串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Page Turning 的本地化字符串。
        /// </summary>
        internal static string AutomaticPageTurning {
            get {
                return ResourceManager.GetString("AutomaticPageTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, the page will automatically turn when the playback pointer reaches the right edge of the page. 的本地化字符串。
        /// </summary>
        internal static string AutomaticPageTurningTooltip {
            get {
                return ResourceManager.GetString("AutomaticPageTurningTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary Tools 的本地化字符串。
        /// </summary>
        internal static string AuxiliaryTools {
            get {
                return ResourceManager.GetString("AuxiliaryTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        internal static string BackText {
            get {
                return ResourceManager.GetString("BackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bar 的本地化字符串。
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bar can&apos;t be negative 的本地化字符串。
        /// </summary>
        internal static string BarNegativeToast {
            get {
                return ResourceManager.GetString("BarNegativeToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beats per measure 的本地化字符串。
        /// </summary>
        internal static string BeatsPerMeasure {
            get {
                return ResourceManager.GetString("BeatsPerMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bit Depth 的本地化字符串。
        /// </summary>
        internal static string BitDepth {
            get {
                return ResourceManager.GetString("BitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change track color 的本地化字符串。
        /// </summary>
        internal static string ChangeTrackColor {
            get {
                return ResourceManager.GetString("ChangeTrackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close project 的本地化字符串。
        /// </summary>
        internal static string CloseProject {
            get {
                return ResourceManager.GetString("CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the compression file encoding method to ensure the text on the right displays correctly. 的本地化字符串。
        /// </summary>
        internal static string CompressionEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("CompressionEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press back again to cancel the singer installation. 的本地化字符串。
        /// </summary>
        internal static string ConfirmCancelSingerInstallToast {
            get {
                return ResourceManager.GetString("ConfirmCancelSingerInstallToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied to clipboard 的本地化字符串。
        /// </summary>
        internal static string CopiedToClipboardToast {
            get {
                return ResourceManager.GetString("CopiedToClipboardToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy error message 的本地化字符串。
        /// </summary>
        internal static string CopyErrorMessage {
            get {
                return ResourceManager.GetString("CopyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dependency Management 的本地化字符串。
        /// </summary>
        internal static string DependencyManagement {
            get {
                return ResourceManager.GetString("DependencyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect Tempo 的本地化字符串。
        /// </summary>
        internal static string DetectTempo {
            get {
                return ResourceManager.GetString("DetectTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DiffSinger Render Steps for Acoustic Model 的本地化字符串。
        /// </summary>
        internal static string DiffSingerSteps {
            get {
                return ResourceManager.GetString("DiffSingerSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DiffSinger Render Steps for Pitch Prediction Model 的本地化字符串。
        /// </summary>
        internal static string DiffSingerStepsPitch {
            get {
                return ResourceManager.GetString("DiffSingerStepsPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure DiffSinger render steps for pitch prediction model. Lower value means faster inference while higher value means higher quality. 的本地化字符串。
        /// </summary>
        internal static string DiffSingerStepsPitchTooltip {
            get {
                return ResourceManager.GetString("DiffSingerStepsPitchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure DiffSinger render steps for acoustic model. Lower value means faster inference while higher value means higher quality. 的本地化字符串。
        /// </summary>
        internal static string DiffSingerStepsTooltip {
            get {
                return ResourceManager.GetString("DiffSingerStepsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DiffSinger Render Steps for Variance Model 的本地化字符串。
        /// </summary>
        internal static string DiffSingerStepsVariance {
            get {
                return ResourceManager.GetString("DiffSingerStepsVariance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure DiffSinger render steps for singing style (variance) model. Lower value means faster inference while higher value means higher quality. 的本地化字符串。
        /// </summary>
        internal static string DiffSingerStepsVarianceTooltip {
            get {
                return ResourceManager.GetString("DiffSingerStepsVarianceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display Singer Portrait 的本地化字符串。
        /// </summary>
        internal static string DisplaySingerPortrait {
            get {
                return ResourceManager.GetString("DisplaySingerPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upon enabling, the singer&apos;s portrait will appear in the piano roll. 的本地化字符串。
        /// </summary>
        internal static string DisplaySingerPortraitTooltip {
            get {
                return ResourceManager.GetString("DisplaySingerPortraitTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not render muted tracks 的本地化字符串。
        /// </summary>
        internal static string DontRenderMutedTracks {
            get {
                return ResourceManager.GetString("DontRenderMutedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip muted tracks during rendering. 的本地化字符串。
        /// </summary>
        internal static string DontRenderMutedTracksTooltip {
            get {
                return ResourceManager.GetString("DontRenderMutedTracksTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t save 的本地化字符串。
        /// </summary>
        internal static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dry-to-Wet Conversion 的本地化字符串。
        /// </summary>
        internal static string DryWetConversion {
            get {
                return ResourceManager.GetString("DryWetConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit &amp; Behaviour 的本地化字符串。
        /// </summary>
        internal static string EditAndBehaviour {
            get {
                return ResourceManager.GetString("EditAndBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Lyrics 的本地化字符串。
        /// </summary>
        internal static string EditLyrics {
            get {
                return ResourceManager.GetString("EditLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter a valid number 的本地化字符串。
        /// </summary>
        internal static string EnterValidNumberToast {
            get {
                return ResourceManager.GetString("EnterValidNumberToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eraser 的本地化字符串。
        /// </summary>
        internal static string Eraser {
            get {
                return ResourceManager.GetString("Eraser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error: {0} 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project file can&apos;t be opened. It may be due to an unsupported format or a corrupted file. 的本地化字符串。
        /// </summary>
        internal static string ErrorFailLoadProject {
            get {
                return ResourceManager.GetString("ErrorFailLoadProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Message 的本地化字符串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau backend initialization failed 的本地化字符串。
        /// </summary>
        internal static string ErrorOpenUtauBackendInitializationFailed {
            get {
                return ResourceManager.GetString("ErrorOpenUtauBackendInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unfortunately, OpenUtau Mobile has encountered an exception, and some features may not function properly.
        ///We recommend copying the following error message and providing it to the developer, then restarting the application.
        ///
        ///{0}
        ///
        ///Exception Details:
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string ErrorPopupTemplate {
            get {
                return ResourceManager.GetString("ErrorPopupTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Audio 的本地化字符串。
        /// </summary>
        internal static string ExportAudio {
            get {
                return ResourceManager.GetString("ExportAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Logs 的本地化字符串。
        /// </summary>
        internal static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Project 的本地化字符串。
        /// </summary>
        internal static string ExportProject {
            get {
                return ResourceManager.GetString("ExportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File &amp; Storage 的本地化字符串。
        /// </summary>
        internal static string FileAndStorage {
            get {
                return ResourceManager.GetString("FileAndStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find such file 的本地化字符串。
        /// </summary>
        internal static string FileNotFoundToast {
            get {
                return ResourceManager.GetString("FileNotFoundToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Head over to GitHub to suggest improvements, contribute code, or give the project a star. 的本地化字符串。
        /// </summary>
        internal static string GitHubSuggestionsText {
            get {
                return ResourceManager.GetString("GitHubSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Portrait Transparency 的本地化字符串。
        /// </summary>
        internal static string GlobalPortraitTransparency {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable this option to override the transparency presets for all singer portraits. 的本地化字符串。
        /// </summary>
        internal static string GlobalPortraitTransparencyTooltip {
            get {
                return ResourceManager.GetString("GlobalPortraitTransparencyTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hand 的本地化字符串。
        /// </summary>
        internal static string Hand {
            get {
                return ResourceManager.GetString("Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help &amp; Tutorial 的本地化字符串。
        /// </summary>
        internal static string HelpAndTutorial {
            get {
                return ResourceManager.GetString("HelpAndTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help make OpenUtau Mobile better! 的本地化字符串。
        /// </summary>
        internal static string HelpGetBetterText {
            get {
                return ResourceManager.GetString("HelpGetBetterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Audio 的本地化字符串。
        /// </summary>
        internal static string ImportAudio {
            get {
                return ResourceManager.GetString("ImportAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import MIDI 的本地化字符串。
        /// </summary>
        internal static string ImportMidi {
            get {
                return ResourceManager.GetString("ImportMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Track 的本地化字符串。
        /// </summary>
        internal static string ImportTrack {
            get {
                return ResourceManager.GetString("ImportTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Importing Tracks 的本地化字符串。
        /// </summary>
        internal static string ImportTracksCaption {
            get {
                return ResourceManager.GetString("ImportTracksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the correct project file. 的本地化字符串。
        /// </summary>
        internal static string IncorrectProjectFileToast {
            get {
                return ResourceManager.GetString("IncorrectProjectFileToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initialization complete! 的本地化字符串。
        /// </summary>
        internal static string InitializationComplete {
            get {
                return ResourceManager.GetString("InitializationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing DocManager 的本地化字符串。
        /// </summary>
        internal static string InitializingDocManager {
            get {
                return ResourceManager.GetString("InitializingDocManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing Language Localization 的本地化字符串。
        /// </summary>
        internal static string InitializingLanguageLocalization {
            get {
                return ResourceManager.GetString("InitializingLanguageLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing ObjectProvider 的本地化字符串。
        /// </summary>
        internal static string InitializingObjectProvider {
            get {
                return ResourceManager.GetString("InitializingObjectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing PianoRoll 的本地化字符串。
        /// </summary>
        internal static string InitializingPianoRoll {
            get {
                return ResourceManager.GetString("InitializingPianoRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing PlaybackManager 的本地化字符串。
        /// </summary>
        internal static string InitializingPlaybackManager {
            get {
                return ResourceManager.GetString("InitializingPlaybackManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing SingerManager 的本地化字符串。
        /// </summary>
        internal static string InitializingSingerManager {
            get {
                return ResourceManager.GetString("InitializingSingerManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initializing ToolsManager 的本地化字符串。
        /// </summary>
        internal static string InitializingToolsManager {
            get {
                return ResourceManager.GetString("InitializingToolsManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert signature marker 的本地化字符串。
        /// </summary>
        internal static string InsertSignatureMarker {
            get {
                return ResourceManager.GetString("InsertSignatureMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert tempo marker 的本地化字符串。
        /// </summary>
        internal static string InsertTempoMarker {
            get {
                return ResourceManager.GetString("InsertTempoMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert tempo or signature marker 的本地化字符串。
        /// </summary>
        internal static string InsertTempoSignatureMarker {
            get {
                return ResourceManager.GetString("InsertTempoSignatureMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation cancelled! 的本地化字符串。
        /// </summary>
        internal static string InstallationCancelledToast {
            get {
                return ResourceManager.GetString("InstallationCancelledToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation complete! 的本地化字符串。
        /// </summary>
        internal static string InstallationComplete {
            get {
                return ResourceManager.GetString("InstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation Directory 的本地化字符串。
        /// </summary>
        internal static string InstallationDirectoryText {
            get {
                return ResourceManager.GetString("InstallationDirectoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation failed! 的本地化字符串。
        /// </summary>
        internal static string InstallationFailed {
            get {
                return ResourceManager.GetString("InstallationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation Path: 的本地化字符串。
        /// </summary>
        internal static string InstallationPath {
            get {
                return ResourceManager.GetString("InstallationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation Size 的本地化字符串。
        /// </summary>
        internal static string InstallationSizeText {
            get {
                return ResourceManager.GetString("InstallationSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installation Summary 的本地化字符串。
        /// </summary>
        internal static string InstallationSummary {
            get {
                return ResourceManager.GetString("InstallationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installing... 的本地化字符串。
        /// </summary>
        internal static string InstallingText {
            get {
                return ResourceManager.GetString("InstallingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install singers to additional singers path 的本地化字符串。
        /// </summary>
        internal static string InstallToAdditionalSingersPath {
            get {
                return ResourceManager.GetString("InstallToAdditionalSingersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If enabled, singers will be installed into additional singer path that you set above by default. 的本地化字符串。
        /// </summary>
        internal static string InstallToAdditionalSingersPathTooltip {
            get {
                return ResourceManager.GetString("InstallToAdditionalSingersPathTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beats per measure can&apos;t be less than or equal to 0 的本地化字符串。
        /// </summary>
        internal static string InvalidBeatsPerMeasureToast {
            get {
                return ResourceManager.GetString("InvalidBeatsPerMeasureToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BPM can&apos;t be less than or equal to 0 的本地化字符串。
        /// </summary>
        internal static string InvalidBPMToast {
            get {
                return ResourceManager.GetString("InvalidBPMToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notes per beat can&apos;t be less than or equal to 0 的本地化字符串。
        /// </summary>
        internal static string InvalidNotesPerBeatToast {
            get {
                return ResourceManager.GetString("InvalidNotesPerBeatToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep screen on 的本地化字符串。
        /// </summary>
        internal static string KeepScreenOn {
            get {
                return ResourceManager.GetString("KeepScreenOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After enabling, the screen will remain on when editing. 的本地化字符串。
        /// </summary>
        internal static string KeepScreenOnTooltip {
            get {
                return ResourceManager.GetString("KeepScreenOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string Languages_de {
            get {
                return ResourceManager.GetString("Languages_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Languages_en {
            get {
                return ResourceManager.GetString("Languages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spanish 的本地化字符串。
        /// </summary>
        internal static string Languages_es {
            get {
                return ResourceManager.GetString("Languages_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string Languages_fr {
            get {
                return ResourceManager.GetString("Languages_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not translate 的本地化字符串。
        /// </summary>
        internal static string Languages_invariant {
            get {
                return ResourceManager.GetString("Languages_invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italian 的本地化字符串。
        /// </summary>
        internal static string Languages_it {
            get {
                return ResourceManager.GetString("Languages_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string Languages_ja {
            get {
                return ResourceManager.GetString("Languages_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        internal static string Languages_ko {
            get {
                return ResourceManager.GetString("Languages_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Polish 的本地化字符串。
        /// </summary>
        internal static string Languages_pl {
            get {
                return ResourceManager.GetString("Languages_pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Portuguese 的本地化字符串。
        /// </summary>
        internal static string Languages_pt {
            get {
                return ResourceManager.GetString("Languages_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Russian 的本地化字符串。
        /// </summary>
        internal static string Languages_ru {
            get {
                return ResourceManager.GetString("Languages_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thai 的本地化字符串。
        /// </summary>
        internal static string Languages_th {
            get {
                return ResourceManager.GetString("Languages_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vietnamese 的本地化字符串。
        /// </summary>
        internal static string Languages_vi {
            get {
                return ResourceManager.GetString("Languages_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string Languages_zh {
            get {
                return ResourceManager.GetString("Languages_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cantonese 的本地化字符串。
        /// </summary>
        internal static string Languages_zh_yue {
            get {
                return ResourceManager.GetString("Languages_zh_yue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading 的本地化字符串。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Pitch Rendering Result 的本地化字符串。
        /// </summary>
        internal static string LoadPitchRenderingResult {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retrieve the renderer&apos;s recommended pitch curve. However, the rendered result will overwrite existing pitch data. Proceed? 的本地化字符串。
        /// </summary>
        internal static string LoadPitchRenderingResultPrompt {
            get {
                return ResourceManager.GetString("LoadPitchRenderingResultPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Expressions 的本地化字符串。
        /// </summary>
        internal static string ManageExpressions {
            get {
                return ResourceManager.GetString("ManageExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mark beats as 的本地化字符串。
        /// </summary>
        internal static string MarkBeatsAs {
            get {
                return ResourceManager.GetString("MarkBeatsAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MixDown 的本地化字符串。
        /// </summary>
        internal static string MixDown {
            get {
                return ResourceManager.GetString("MixDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mixing Mode 的本地化字符串。
        /// </summary>
        internal static string MixingMode {
            get {
                return ResourceManager.GetString("MixingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More 的本地化字符串。
        /// </summary>
        internal static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New File 的本地化字符串。
        /// </summary>
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Part 的本地化字符串。
        /// </summary>
        internal static string NewPart {
            get {
                return ResourceManager.GetString("NewPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Track 的本地化字符串。
        /// </summary>
        internal static string NewTrack {
            get {
                return ResourceManager.GetString("NewTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No colors are available 的本地化字符串。
        /// </summary>
        internal static string NoColorsAvailable {
            get {
                return ResourceManager.GetString("NoColorsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No dependencies have been installed yet. Click &quot;+&quot; to install from a file. 的本地化字符串。
        /// </summary>
        internal static string NoDependencyPrompt {
            get {
                return ResourceManager.GetString("NoDependencyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No projects have been opened yet. 的本地化字符串。
        /// </summary>
        internal static string NoProjectsOpened {
            get {
                return ResourceManager.GetString("NoProjectsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t quantize yet! Please report this issue to the community. 的本地化字符串。
        /// </summary>
        internal static string NoQuantization {
            get {
                return ResourceManager.GetString("NoQuantization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t select keys yet! Please report the issue to the community. 的本地化字符串。
        /// </summary>
        internal static string NoSelectableKeys {
            get {
                return ResourceManager.GetString("NoSelectableKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No singer installed, please click &quot;+&quot; to add one! 的本地化字符串。
        /// </summary>
        internal static string NoSingerPrompt {
            get {
                return ResourceManager.GetString("NoSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No singers have been added yet. Please go to the singer management page to add them! 的本地化字符串。
        /// </summary>
        internal static string NoSingersText {
            get {
                return ResourceManager.GetString("NoSingersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notes per beat 的本地化字符串。
        /// </summary>
        internal static string NotesPerBeat {
            get {
                return ResourceManager.GetString("NotesPerBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} parts selected 的本地化字符串。
        /// </summary>
        internal static string NPartsSelected {
            get {
                return ResourceManager.GetString("NPartsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On piano click 的本地化字符串。
        /// </summary>
        internal static string OnPianoClick {
            get {
                return ResourceManager.GetString("OnPianoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piano Sample TODO 的本地化字符串。
        /// </summary>
        internal static string OnPianoClickPianoSample {
            get {
                return ResourceManager.GetString("OnPianoClickPianoSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silence 的本地化字符串。
        /// </summary>
        internal static string OnPianoClickSilence {
            get {
                return ResourceManager.GetString("OnPianoClickSilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sine Wave TODO 的本地化字符串。
        /// </summary>
        internal static string OnPianoClickSineWave {
            get {
                return ResourceManager.GetString("OnPianoClickSineWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the behavior for clicking the keys on the left side of the piano roll 的本地化字符串。
        /// </summary>
        internal static string OnPianoClickTooltip {
            get {
                return ResourceManager.GetString("OnPianoClickTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Core version 的本地化字符串。
        /// </summary>
        internal static string OpenUtauCoreVersion {
            get {
                return ResourceManager.GetString("OpenUtauCoreVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenUtau Mobile version 的本地化字符串。
        /// </summary>
        internal static string OpenUtauMobileVersion {
            get {
                return ResourceManager.GetString("OpenUtauMobileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output device 的本地化字符串。
        /// </summary>
        internal static string OutputDevice {
            get {
                return ResourceManager.GetString("OutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Android: view only, can&apos;t edit. 的本地化字符串。
        /// </summary>
        internal static string OutputDeviceTooltip {
            get {
                return ResourceManager.GetString("OutputDeviceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phonemizing in progress: 的本地化字符串。
        /// </summary>
        internal static string PhonemizingInProgress {
            get {
                return ResourceManager.GetString("PhonemizingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Piano Roll Quantization 的本地化字符串。
        /// </summary>
        internal static string PianoRollQuantization {
            get {
                return ResourceManager.GetString("PianoRollQuantization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pitch display precision 的本地化字符串。
        /// </summary>
        internal static string PitchDisplayPrecision {
            get {
                return ResourceManager.GetString("PitchDisplayPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Higher precision can more accurately depict actual pitch, but may lead to performance issues. 的本地化字符串。
        /// </summary>
        internal static string PitchDisplayPrecisionTooltip {
            get {
                return ResourceManager.GetString("PitchDisplayPrecisionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fine 的本地化字符串。
        /// </summary>
        internal static string PitchPrecisionFine {
            get {
                return ResourceManager.GetString("PitchPrecisionFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        internal static string PitchPrecisionMedium {
            get {
                return ResourceManager.GetString("PitchPrecisionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original 的本地化字符串。
        /// </summary>
        internal static string PitchPrecisionOriginal {
            get {
                return ResourceManager.GetString("PitchPrecisionOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rough 的本地化字符串。
        /// </summary>
        internal static string PitchPrecisionRough {
            get {
                return ResourceManager.GetString("PitchPrecisionRough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Playback refresh rate 的本地化字符串。
        /// </summary>
        internal static string PlaybackRefreshRate {
            get {
                return ResourceManager.GetString("PlaybackRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the refresh rate for the playback pointer, ranging from 1 to 60 FPS. Adjust this setting based on your device&apos;s performance. Excessively high refresh rates may cause stuttering. Changes to this setting take effect after reopening the editing page. 的本地化字符串。
        /// </summary>
        internal static string PlaybackRefreshRateTooltip {
            get {
                return ResourceManager.GetString("PlaybackRefreshRateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position can&apos;t be negative 的本地化字符串。
        /// </summary>
        internal static string PositionNegativeToast {
            get {
                return ResourceManager.GetString("PositionNegativeToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-render 的本地化字符串。
        /// </summary>
        internal static string PreRender {
            get {
                return ResourceManager.GetString("PreRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pre-render audio in the background before playback. 的本地化字符串。
        /// </summary>
        internal static string PreRenderTooltip {
            get {
                return ResourceManager.GetString("PreRenderTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing waveform... 的本地化字符串。
        /// </summary>
        internal static string ProcessingWaveform {
            get {
                return ResourceManager.GetString("ProcessingWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waveform processing has been canceled. 的本地化字符串。
        /// </summary>
        internal static string ProcessingWaveformCancelled {
            get {
                return ResourceManager.GetString("ProcessingWaveformCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waveform data is empty. 的本地化字符串。
        /// </summary>
        internal static string ProcessingWaveformEmpty {
            get {
                return ResourceManager.GetString("ProcessingWaveformEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waveform Processing Error: {0} 的本地化字符串。
        /// </summary>
        internal static string ProcessingWaveformError {
            get {
                return ResourceManager.GetString("ProcessingWaveformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waveform processing hasn&apos;t yet started. 的本地化字符串。
        /// </summary>
        internal static string ProcessingWaveformNotStarted {
            get {
                return ResourceManager.GetString("ProcessingWaveformNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress: 的本地化字符串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quantize 的本地化字符串。
        /// </summary>
        internal static string QuantizeText {
            get {
                return ResourceManager.GetString("QuantizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent 的本地化字符串。
        /// </summary>
        internal static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recent Projects 的本地化字符串。
        /// </summary>
        internal static string RecentProjects {
            get {
                return ResourceManager.GetString("RecentProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove dependency {0}? 的本地化字符串。
        /// </summary>
        internal static string RemoveDependencyPrompt {
            get {
                return ResourceManager.GetString("RemoveDependencyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Dependency 的本地化字符串。
        /// </summary>
        internal static string RemoveDependencyTitle {
            get {
                return ResourceManager.GetString("RemoveDependencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Singer 的本地化字符串。
        /// </summary>
        internal static string RemoveSinger {
            get {
                return ResourceManager.GetString("RemoveSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to remove singer {0} 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerFailureToast {
            get {
                return ResourceManager.GetString("RemoveSingerFailureToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove singer {0}? 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerPrompt {
            get {
                return ResourceManager.GetString("RemoveSingerPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully removed singer {0} 的本地化字符串。
        /// </summary>
        internal static string RemoveSingerSuccessToast {
            get {
                return ResourceManager.GetString("RemoveSingerSuccessToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing Dependency {0} 的本地化字符串。
        /// </summary>
        internal static string RemovingDependencyMessage {
            get {
                return ResourceManager.GetString("RemovingDependencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Removing singer {0}... 的本地化字符串。
        /// </summary>
        internal static string RemovingSingerToast {
            get {
                return ResourceManager.GetString("RemovingSingerToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Part 的本地化字符串。
        /// </summary>
        internal static string RenamePart {
            get {
                return ResourceManager.GetString("RenamePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename Track 的本地化字符串。
        /// </summary>
        internal static string RenameTrack {
            get {
                return ResourceManager.GetString("RenameTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render 的本地化字符串。
        /// </summary>
        internal static string Render {
            get {
                return ResourceManager.GetString("Render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Render &amp; Performance 的本地化字符串。
        /// </summary>
        internal static string RenderAndPerformance {
            get {
                return ResourceManager.GetString("RenderAndPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering waveform file... 的本地化字符串。
        /// </summary>
        internal static string RenderingWaveformFile {
            get {
                return ResourceManager.GetString("RenderingWaveformFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart the program 的本地化字符串。
        /// </summary>
        internal static string RestartProgram {
            get {
                return ResourceManager.GetString("RestartProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/{0} measure ({0}th note) 的本地化字符串。
        /// </summary>
        internal static string RhythmMeasureNoteTemplate {
            get {
                return ResourceManager.GetString("RhythmMeasureNoteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sample Rate 的本地化字符串。
        /// </summary>
        internal static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved 的本地化字符串。
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save File 的本地化字符串。
        /// </summary>
        internal static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Project As 的本地化字符串。
        /// </summary>
        internal static string SaveProjectAs {
            get {
                return ResourceManager.GetString("SaveProjectAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string SaveText {
            get {
                return ResourceManager.GetString("SaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select an Expression 的本地化字符串。
        /// </summary>
        internal static string SelectExpression {
            get {
                return ResourceManager.GetString("SelectExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select File 的本地化字符串。
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a file 的本地化字符串。
        /// </summary>
        internal static string SelectFileToast {
            get {
                return ResourceManager.GetString("SelectFileToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Phonemizer 的本地化字符串。
        /// </summary>
        internal static string SelectPhonemizer {
            get {
                return ResourceManager.GetString("SelectPhonemizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select where to save the file 的本地化字符串。
        /// </summary>
        internal static string SelectSaveLocationToast {
            get {
                return ResourceManager.GetString("SelectSaveLocationToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Singer 的本地化字符串。
        /// </summary>
        internal static string SelectSinger {
            get {
                return ResourceManager.GetString("SelectSinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Separate Stems 的本地化字符串。
        /// </summary>
        internal static string SeparateStems {
            get {
                return ResourceManager.GetString("SeparateStems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set beat 的本地化字符串。
        /// </summary>
        internal static string SetBeat {
            get {
                return ResourceManager.GetString("SetBeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set BPM 的本地化字符串。
        /// </summary>
        internal static string SetBPM {
            get {
                return ResourceManager.GetString("SetBPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set key 的本地化字符串。
        /// </summary>
        internal static string SetKey {
            get {
                return ResourceManager.GetString("SetKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set tempo for tick marker to 的本地化字符串。
        /// </summary>
        internal static string SetTempoTickMarker {
            get {
                return ResourceManager.GetString("SetTempoTickMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved! 的本地化字符串。
        /// </summary>
        internal static string SettingsSavedToast {
            get {
                return ResourceManager.GetString("SettingsSavedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred while saving settings. 的本地化字符串。
        /// </summary>
        internal static string SettingsSaveErrorToast {
            get {
                return ResourceManager.GetString("SettingsSaveErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... (Showing first {0} entries) 的本地化字符串。
        /// </summary>
        internal static string ShowingFirstNEntries {
            get {
                return ResourceManager.GetString("ShowingFirstNEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... (Showing first {0} text files) 的本地化字符串。
        /// </summary>
        internal static string ShowingFirstNTextFiles {
            get {
                return ResourceManager.GetString("ShowingFirstNTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer 的本地化字符串。
        /// </summary>
        internal static string Singer {
            get {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer information is missing. Please select the singer type: 的本地化字符串。
        /// </summary>
        internal static string SingerInformationMissing {
            get {
                return ResourceManager.GetString("SingerInformationMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Singers 的本地化字符串。
        /// </summary>
        internal static string SingerManage {
            get {
                return ResourceManager.GetString("SingerManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer Name 的本地化字符串。
        /// </summary>
        internal static string SingerNameText {
            get {
                return ResourceManager.GetString("SingerNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singers 的本地化字符串。
        /// </summary>
        internal static string Singers {
            get {
                return ResourceManager.GetString("Singers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer Setup Wizard 的本地化字符串。
        /// </summary>
        internal static string SingerSetupWizard {
            get {
                return ResourceManager.GetString("SingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Singer Type 的本地化字符串。
        /// </summary>
        internal static string SingerTypeText {
            get {
                return ResourceManager.GetString("SingerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage permission denied 的本地化字符串。
        /// </summary>
        internal static string StoragePermissionDeniedToast {
            get {
                return ResourceManager.GetString("StoragePermissionDeniedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        internal static string StringHomePage {
            get {
                return ResourceManager.GetString("StringHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Press back button again to exit OpenUtau Mobile 的本地化字符串。
        /// </summary>
        internal static string StringPressBackAgainToExit {
            get {
                return ResourceManager.GetString("StringPressBackAgainToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully deleted! 的本地化字符串。
        /// </summary>
        internal static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap 的本地化字符串。
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select the text encoding method to ensure the text on the right displays correctly. 的本地化字符串。
        /// </summary>
        internal static string TextEncodingMethodPrompt {
            get {
                return ResourceManager.GetString("TextEncodingMethodPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark or light theme 的本地化字符串。
        /// </summary>
        internal static string ThemeTooltip {
            get {
                return ResourceManager.GetString("ThemeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tick Time 的本地化字符串。
        /// </summary>
        internal static string TickTime {
            get {
                return ResourceManager.GetString("TickTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transparency 的本地化字符串。
        /// </summary>
        internal static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown Error 的本地化字符串。
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown status: {0} 的本地化字符串。
        /// </summary>
        internal static string UnknownStatus {
            get {
                return ResourceManager.GetString("UnknownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are unsaved changes. Do you want to save and exit? 的本地化字符串。
        /// </summary>
        internal static string UnsavedProjectChangesPrompt {
            get {
                return ResourceManager.GetString("UnsavedProjectChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vocal track only 的本地化字符串。
        /// </summary>
        internal static string VocalTrackOnly {
            get {
                return ResourceManager.GetString("VocalTrackOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vogen Singer will be installed soon... 的本地化字符串。
        /// </summary>
        internal static string VogenSingerInstalledSoon {
            get {
                return ResourceManager.GetString("VogenSingerInstalledSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vogen Singer Setup Wizard 的本地化字符串。
        /// </summary>
        internal static string VogenSingerSetupWizard {
            get {
                return ResourceManager.GetString("VogenSingerSetupWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have permission to access this directory. 的本地化字符串。
        /// </summary>
        internal static string WarningNoDirectoryPermission {
            get {
                return ResourceManager.GetString("WarningNoDirectoryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no directories or files matching the criteria in this directory. 的本地化字符串。
        /// </summary>
        internal static string WarningNoDirOrFilesMatchingCriteria {
            get {
                return ResourceManager.GetString("WarningNoDirOrFilesMatchingCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Website: 的本地化字符串。
        /// </summary>
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting... 的本地化字符串。
        /// </summary>
        internal static string WorkTitleExport {
            get {
                return ResourceManager.GetString("WorkTitleExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading project, Don&apos;t touch 的本地化字符串。
        /// </summary>
        internal static string WorkTitleLoadingProject {
            get {
                return ResourceManager.GetString("WorkTitleLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working... 的本地化字符串。
        /// </summary>
        internal static string WorkTitleOther {
            get {
                return ResourceManager.GetString("WorkTitleOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phonemizing... 的本地化字符串。
        /// </summary>
        internal static string WorkTitlePhonemize {
            get {
                return ResourceManager.GetString("WorkTitlePhonemize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering waveform... 的本地化字符串。
        /// </summary>
        internal static string WorkTitleReadWave {
            get {
                return ResourceManager.GetString("WorkTitleReadWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering... 的本地化字符串。
        /// </summary>
        internal static string WorkTitleRender {
            get {
                return ResourceManager.GetString("WorkTitleRender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rendering the pitch... 的本地化字符串。
        /// </summary>
        internal static string WorkTitleRenderPitch {
            get {
                return ResourceManager.GetString("WorkTitleRenderPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select a valid file *{0} 的本地化字符串。
        /// </summary>
        internal static string WrongFileTypeToast {
            get {
                return ResourceManager.GetString("WrongFileTypeToast", resourceCulture);
            }
        }
    }
}
